name: workflow teste
run-name: teste


on:  
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
  web-tests:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./